version: '3'

services:
  mysqldb:
    image: mysql:8.1.0
    ports:
      - "${MYSQL_DB_PORT}:3306"
    environment:
#      - MYSQL_INITDB_DATABASE=patients
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=patients

  patient-app:
    image: hamza3991/patients:0.0.1
    ports:
      - "${PATIENT_APP_PORT}:${PATIENT_APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:${MYSQL_DB_PORT}/patients?allowPublicKeyRetrieval=true&useSSL=false
#      - "spring.datasource.url" : "jdbc:mysql://mysql:3306/abernathyclinic?allowPublicKeyRetrieval=true&useSSL=false",
      - SPRING.JPA.HIBERNATE.DDL-AUTO=update

    depends_on:
      - mysqldb
    command: bash -c "sleep 20; start.sh" # Waiting for MySQL to start
    restart: on-failure

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=note

  note-app:
    image: hamza3991/notes:0.0.1
    ports:
      - "${NOTE_APP_PORT}:${NOTE_APP_PORT}"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:${MONGO_DB_PORT}/note
      - PATIENT_URL=http://patient-app:${PATIENT_APP_PORT}
    depends_on:
      - mongodb

  report-app:
    image: hamza3991/reports:0.0.1
    ports:
      - "${REPORT_APP_PORT}:${REPORT_APP_PORT}"
    environment:
      - NOTE_URL=http://note-app:${NOTE_APP_PORT}
      - PATIENT_URL=http://patient-app:${PATIENT_APP_PORT}
    depends_on:
      - patient-app
      - note-app


  webinterface-app:
    image: hamza3991/webinterface:0.0.1
    ports:
      - "${WEBINTERFACE_APP_PORT}:${WEBINTERFACE_APP_PORT}"
    environment:
      - NOTE_URL=http://note-app:${NOTE_APP_PORT}
      - PATIENT_URL=http://patient-app:${PATIENT_APP_PORT}
      - REPORT_URL=http://report-app:${REPORT_APP_PORT}
    depends_on:
      - patient-app
      - note-app
      - report-app




